blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/7fQPG4Grwt
    about: Join our Discord for quick help and support
  - name: Documentation
    url: https://vanillacore.tejaslamba.com
    about: Check the documentation for guides and information
